
export { default as dot } from './dot.js'
export { default as evaluate } from './evaluate.js'
export { default as footnote } from './footnote.js'
export { default as formatDate } from './formatDate.js'
export { default as getCI } from './getCI.js'
export { default as match } from './match.js'
export { default as numberValue } from './numberValue.js'
export { default as objCopy } from './objCopy.js'
export { default as typeOf } from './typeOf.js'
