/**
 * client/account.js
 */

import Roles from './roles.js'

const guest = {
  userid: 'guest',
  password: 'guest',
  _state: {
    isAuthenticated: false
  }
}

export default class Account {

  constructor(user = guest) {
    this.clear()
    this.userid = user.userid
    this.password = user.password
  }

  clear() {
    this.userid = 'guest'
    this.password = 'guest'
    this.roles = [ Roles.Public, Roles.Guest ]
    this.dateCreated = null
    this.dateUpdated = null
    this.lastLogin = null

    // state can be copied, but shouldn't be saved or serialized
    this._state = {
      isAuthenticated: false
    }

    this.profile = {
      provider: '', // The provider with which the user authenticated (facebook, twitter, etc.).
      id: '', // A unique identifier for the user, as generated by the service provider.
      displayName: '', // The name of this user, suitable for display.
      name: {
        familyName: '', // The family name of this user, or "last name" in most Western languages.
        givenName: '', // The given name of this user, or "first name" in most Western languages.
        middleName: '' // The middle name of this user.
      },
      emails: [ {
        email: '', // The actual email address.
        type: '' // The type of email address (home, work, etc.).
      } ],
      photos: [ {
        value: '' // The URL of the image.
      } ]
    }

    this.settings = {
      prefix: '',
      homepage: '',
      darkmode: '',
      theme: ''
    }
  }

  /**
   * returns true if user is Authenticated i.e. logged in
   */
  get isAuthenticated() {
    return (this._state && this._state.isAuthenticated) || false
  }
  set isAuthenticated(value) {
    if (!this._state)
      this._state = {}
    this._state.isAuthenticated = value
  }

  /**
   * isAuthorized returns true if user has at least one of the requested role(s).
   * @param {*} role as a string or array of strings
   */
  isAuthorized(roles) {
    if (Array.isArray(roles)) {
      for (let i = 0; i < roles.length; i++) {
        if (this.roles.includes(roles[ i ]))
          return true
      }
    } else if (roles)
      return this.roles.includes(roles)

    return false
  }

  /**
   * helper for accessing state
   */
  get state() {
    if (!this._state)
      this._state = {}
    return this._state
  }

  // shallow copy of all non-function properties
  copy(u2) {
    let u1 = this

    Object.keys(u2).forEach(function (key) {
      let t = typeof u2[ key ]
      if (t !== "undefined" && t !== "function")
        u1[ key ] = u2[ key ]
    })
  }

  // shallow copy of non-function properties
  // excluding userid, password, state
  update(u2) {
    let u1 = this

    Object.keys(u2).forEach(function (key) {
      let t = typeof u2[ key ]

      if (key === 'userid' || key === 'password' || key === '_state') {
        //
      } else if (t !== "undefined" && t !== "function")
        u1[ key ] = u2[ key ]
    })
  }

}
