###
POST http://dev.dictadata.org/node/tracts HTTP/1.1
Authorization: Basic user user
Content-Type: application/json; charset=utf-8

{
  "pattern": {
    "match": {
      "type": ["alias","tract"],
      "~search": {
        "search": "foo",
        "fields": [ "name", "domain", "tags", "title", "type", "source", "description" ],
        "op": "AND"
      }
    }
  }
}
